<p>Etês-vous sur de vouloir supprimer le client :
    '<?php echo $this->locataire['NUMEROLOC']." (identifiant: ".$this->locataire['NUMEROLOC'].")"; ?>'? 
</p>
<form action="<?php echo $this->url(array('controller'=>'locataire','action'=>'supprimer')); ?> " method="post">
<div>
    <input type="hidden" name="NUMEROLOC" value="<?php echo $this->locataire['NUMEROLOC']; ?>" />
    <input type="submit" name="supprimer" value="Oui" />
    <input type="submit" name="supprimer" value="Non" />
</div>   
</form>