<p><a href="http://localhost/world2base">Accueil</a>
<p><a href="http://localhost/world2base/appartement/">Gestion Appartement</a>

<table border='1'>

    <tr>
       <th>Id</th>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Date de naissance</th>
        <th>Tel</th>
        <th>RIB</th>
        <th>BANQUE</th>
        <th>RUE BANQUE</th>
        <th>CODEVILLE_BANQUE</th>
        <th>TEL BANQUE</th>
    </tr>
    <tr>
        <td><?php echo $this->locataire['NUMEROLOC'] ?></td>
        <td><?php echo $this->locataire['NOM_LOC'] ?></td>
        <td><?php echo $this->locataire['PRENOM_LOC'] ?></td>
        <td><?php echo $this->locataire['DATENAISS'] ?></td>
        <td><?php echo $this->locataire['TEL_LOC'] ?></td>
        <td><?php echo $this->locataire['R_I_B'] ?></td>
        <td><?php echo $this->locataire['BANQUE'] ?></td>
        <td><?php echo $this->locataire['RUE_BANQUE'] ?></td>
        <td><?php echo $this->locataire['CODEVILLE_BANQUE'] ?></td>
        <td><?php echo $this->locataire['TEL_BANQUE'] ?></td>
    </tr>    
</table>

