<p><a href="http://localhost/world2base">Accueil</a>
<p><a href="http://localhost/world2base/appartement">Gestion Appartement</a>

<table border='1'>
    <th>NUMEROPROP</th>
    <th>NOM</th>
    <th>PRENOM</th>
    <th>DATE NAISSANCE</th>
    <th>CODEVILLE</th>
    <th>TEL</th>



    <tr>

        <td><?php echo $this->proprietaire['NUMEROPROP'] ?></td>
        <td><?php echo $this->proprietaire['NOM'] ?></td>
        <td><?php echo $this->proprietaire['PRENOM'] ?></td>
        <td><?php echo $this->proprietaire['ADRESSE'] ?></td>
        <td><?php echo $this->proprietaire['CODE_VILLE'] ?></td>
        <td><?php echo $this->proprietaire['TEL'] ?></td>



</table>    
