<p>Etês-vous sur de vouloir supprimer l'appart :
    '<?php echo $this->appartement['NUMAPPART']." (identifiant: ".$this->appartement['NUMAPPART'].")"; ?>'? 
</p>
<form action="<?php echo $this->url(array('controller'=>'appartement','action'=>'supprimer')); ?> " method="post">
<div>
    <input type="hidden" name="NUMAPPART" value="<?php echo $this->appartement['NUMAPPART']; ?>" />
    <input type="submit" name="supprimer" value="Oui" />
    <input type="submit" name="supprimer" value="Non" />
</div>   
</form>