<p>Etês-vous sur de vouloir supprimer le client :
    '<?php echo $this->client['NOM_CLI']." (identifiant: ".$this->client['NUM_CLI'].")"; ?>'? 
</p>
<form action="<?php echo $this->url(array('controller'=>'client','action'=>'supprimer')); ?> " method="post">
<div>
    <input type="hidden" name="NUM_CLI" value="<?php echo $this->client['NUM_CLI']; ?>" />
    <input type="submit" name="supprimer" value="Oui" />
    <input type="submit" name="supprimer" value="Non" />
</div>   
</form>