<br><br>
<div id="view-content">
    <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>"> Retour à la page accueil </a></td>
    <br>
</div>

<table border="1">
    <tr>
        <td>NUM PROPRIO</td>
        <td>NOM</td>
        <td>PRENOM</td>
        <td>ADRESSE</td>
        <td>CODE VILLE</td>
        <td>TEL</td>
        <td>COTISATIONS</td>
        <td>DETAILS</td>
        
    </tr>
    
    <?php
    
    foreach ($this->cotisers as $cotiser) :
        ?>
    
            <tr>
            <td><?php echo $cotiser["NUMEROPROP"];?></td>
            <td><?php echo $cotiser["NOM"];?></td>
            <td><?php echo $cotiser["PRENOM"];?></td>
            <td><?php echo $cotiser["ADRESSE"];?></td>
            <td><?php echo $cotiser["CODE_VILLE"];?></td>
            <td><?php echo $cotiser["TEL"];?></td>
            <td><?php echo $cotiser["COTISATIONS"];?></td>
            <td><a href="<?php echo $this->url(array('controller' => 'proprietaire', 'action'=>'detailscotisations', 'NUMEROPROP'=> $cotiser["NUMEROPROP"])); ?>">Details</a></td>
            
   
        </tr>
    <?php endforeach; 
    ?>
</table>