<p>Etês-vous sur de vouloir supprimer le proprietaire :
    '<?php echo $this->client['NOM']." (identifiant: ".$this->client['NUMEROPROP'].")"; ?>'? 
</p>
<form action="<?php echo $this->url(array('controller'=>'proprietaire','action'=>'supprimer')); ?> " method="post">
<div>
    <input type="hidden" name="NUMEROPROP" value="<?php echo $this->proprietaire['NUMEROPROP']; ?>" />
    <input type="submit" name="supprimer" value="Oui" />
    <input type="submit" name="supprimer" value="Non" />
</div>   
</form>